name: "pre-release"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Build the project
        run: ./build.sh

      - name: Publish to GitHub Packages
        run: ./gradlew publishMavenJavaPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          prerelease: true
          name: "Development Build"
          files: |
            LICENSE
            build/libs/*.jar
